### ISSUE TITLE
My Profile: unable to fill out any form

### ISSUE THREAD

**Issue by wijjj** [entmike/fd-web-ui#30]
I'm trying to use the input masks including Twitter Handle, etc. but both with Google Chrome and Firefox, I am unable to type anything (no characters are appearing in the form).

Steps to reproduce: just login to fever dreams app. Click on "My Profile", start typing.

If I inspect e.g. the about element (id="bio" class="chakra-textarea") [event] says invalid (main.b338ac5d.js:1:215515)

**Comment by entmike** [comment]
Fixed in https://github.com/entmike/fd-web-ui/pull/31
